[application]

# Web `build` & `serve` dist path
out_dir = "dist"

# resource (static) file folder
asset_dir = "assets"

[web.wasm_opt]
# The level wasm-opt should target. z is the smallest. 4 is the fastest.
level = "4"

[web.app]

# HTML title tag content
title = "WrldBldr Player"

[web.watcher]

index_on_404 = true

watch_path = [
  "src",
  "assets",
  "../player-ui/src",
  "../player-ui/assets",
  "../player-ui/styles",
]

[bundle]
# Bundle identifier
identifier = "io.github.wrldbldr-player"

# Bundle publisher
publisher = "wrldbldr-player"

# Bundle icon
# TODO: add icons under crates/player-runner/assets and update this.
icon = []

# Bundle resources
resources = []

# Bundle copyright
copyright = ""

# Bundle category
category = "Utility"

# Bundle short description
short_description = "An amazing dioxus application."

# Bundle long description
long_description = """
An amazing dioxus application.
"""
